// Code generated by mergeb64. DO NOT EDIT.
package example

import "encoding/base64"

var GoMod = func() (data []byte) {
	data, _ = base64.StdEncoding.DecodeString(`` +
		`bW9kdWxlIGdpdGh1Yi5jb20vaGFucGFtYS9tZXJnZWI2NAoKZ28gMS4xMwoKcmVxdWlyZSBnaXRodWIuY29tL2tucS9zbmFr` +
		`ZXIgdjAuMC4wLTIwMTgxMjE1MTQ0MDExLTJiYzhhNGRiNDY4NwoA`,
	)
	return data[:110]
}()

var GoSum = func() (data []byte) {
	data, _ = base64.StdEncoding.DecodeString(`` +
		`Z2l0aHViLmNvbS9rbnEvc25ha2VyIHYwLjAuMC0yMDE4MTIxNTE0NDAxMS0yYmM4YTRkYjQ2ODcgaDE6WnJPWmJxVzdUMkVn` +
		`TGQ0c29SQVRlU1pyUDNpankyQ2dORlhHNDRjVXVTOD0KZ2l0aHViLmNvbS9rbnEvc25ha2VyIHYwLjAuMC0yMDE4MTIxNTE0` +
		`NDAxMS0yYmM4YTRkYjQ2ODcvZ28ubW9kIGgxOmYwRG1xOGZrZGRoOG5Pc1ZhYlltdE9ISGR4bHEycTRYK0xRMXhXUUVkVVU9` +
		`CgAA`,
	)
	return data[:217]
}()
